# test against this version of node.js
environment:
  matrix:
  # node_js
  - nodejs_version: "6"

# install scripts
install:
  # get the latest stable version of nodejs
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# post install test scripts
test_script:
  # output useful information for debugging
  - node --version
  - npm --version
  # run tests
  - npm test

# don't actually build
build: off
